name: CBD
on:
    push:
        branches: gh-pages
jobs:
    cbd:
        name: doc cbd
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: test
              run: npm install & npm run lint
            - name: Build
              run: pnpm run build
            - name: DeployGP
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.CICD}}
                  publish_dir: ./dist
